"""Tests for mltk.report.bias_report -- bias/fairness Markdown report generator.

Each test follows the pattern:
  # SCENARIO: <what situation is being tested>
  # WHY: <why this matters / what could go wrong>
  # EXPECTED: <the concrete assertion>
"""

from __future__ import annotations

import json
from pathlib import Path

from mltk.report.bias_report import generate_bias_report

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _write_results(tmp_path: Path, results: list[dict]) -> Path:
    """Write a list of result dicts to a JSON file and return its path."""
    p = tmp_path / "results.json"
    p.write_text(json.dumps(results), encoding="utf-8")
    return p


def _make_result(
    name: str,
    passed: bool = True,
    message: str = "",
    severity: str = "error",
    details: dict | None = None,
    duration_ms: float = 1.0,
) -> dict:
    return {
        "name": name,
        "passed": passed,
        "message": message,
        "severity": severity,
        "details": details or {},
        "duration_ms": duration_ms,
    }


# ---------------------------------------------------------------------------
# Test 1 — file creation
# ---------------------------------------------------------------------------

def test_generate_report_creates_file(tmp_path: Path) -> None:
    # SCENARIO: generate_bias_report is called with a valid results JSON
    # WHY: The function must produce a file at output_path; if it doesn't,
    #       nothing downstream can consume the report
    # EXPECTED: The output path exists, has a .md suffix, and the returned
    #            Path object matches the output_path argument

    results_path = _write_results(tmp_path, [
        _make_result(
            "model.bias.demographic_parity",
            passed=True,
            details={"method": "demographic_parity"},
        ),
    ])
    out_path = tmp_path / "my-bias-report.md"

    returned = generate_bias_report(results_path, output_path=out_path)

    assert returned == out_path
    assert out_path.exists()
    assert out_path.suffix == ".md"


# ---------------------------------------------------------------------------
# Test 2 — required sections present
# ---------------------------------------------------------------------------

def test_report_has_sections(tmp_path: Path) -> None:
    # SCENARIO: A typical run with one passing and one failing bias test
    # WHY: Report consumers (humans, CI) expect specific section headers;
    #       missing sections make the report unusable
    # EXPECTED: All five section headers (1–4 content + Generated By) appear

    results_path = _write_results(tmp_path, [
        _make_result(
            "model.bias.demographic_parity",
            passed=True,
            message="Parity gap 0.02 < threshold 0.05",
            details={"method": "demographic_parity"},
        ),
        _make_result(
            "model.bias.equalized_odds",
            passed=False,
            message="FPR gap 0.12 exceeds threshold 0.05",
            details={"method": "equalized_odds"},
        ),
    ])
    out_path = tmp_path / "sections-test.md"
    generate_bias_report(results_path, output_path=out_path)

    content = out_path.read_text(encoding="utf-8")

    assert "## 1. Summary" in content
    assert "## 2. Per-Method Breakdown" in content
    assert "## 3. Per-Group Metrics" in content
    assert "## 4. Recommendations" in content
    assert "## 5. Generated By" in content


# ---------------------------------------------------------------------------
# Test 3 — empty results do not crash
# ---------------------------------------------------------------------------

def test_report_empty_results(tmp_path: Path) -> None:
    # SCENARIO: Results JSON contains no bias tests (or is entirely empty)
    # WHY: Users may run the reporter before any bias tests are defined;
    #       a crash here would block the pipeline
    # EXPECTED: File is written successfully; contains graceful "no tests" text

    results_path = _write_results(tmp_path, [
        _make_result("model.metric.accuracy", passed=True),
        _make_result("data.schema.column_types", passed=True),
    ])
    out_path = tmp_path / "empty-bias.md"

    # Should not raise
    returned = generate_bias_report(results_path, output_path=out_path)

    assert returned.exists()
    content = out_path.read_text(encoding="utf-8")
    # "No bias tests found" message should appear somewhere in the file
    assert "No bias tests" in content or "no bias" in content.lower() or "0" in content


# ---------------------------------------------------------------------------
# Test 4 — bias results appear in output
# ---------------------------------------------------------------------------

def test_report_with_bias_results(tmp_path: Path) -> None:
    # SCENARIO: Results contain bias tests with per-group metrics in details
    # WHY: The key value of the report is surfacing per-group disparity;
    #       if group_metrics are not rendered the report misses its purpose
    # EXPECTED: Method name and group labels appear in the Markdown output

    results_path = _write_results(tmp_path, [
        _make_result(
            "model.bias.demographic_parity",
            passed=False,
            message="Parity gap 0.14 exceeds threshold 0.05",
            details={
                "method": "demographic_parity",
                "group_metrics": {
                    "group_a": 0.82,
                    "group_b": 0.68,
                },
            },
        ),
    ])
    out_path = tmp_path / "with-bias.md"
    generate_bias_report(results_path, output_path=out_path)

    content = out_path.read_text(encoding="utf-8")

    # Method name surfaces in per-method breakdown
    assert "demographic_parity" in content
    # Group labels surface in per-group metrics section
    assert "group_a" in content
    assert "group_b" in content
    # Failing test recommendation guidance should appear
    assert "demographic" in content.lower() or "Recommendations" in content
