"""Live portal -- self-contained HTML page for real-time test monitoring.

**Why a live portal:**

The existing mltk dashboard (``dashboard.html``) shows *historical* results --
runs that already completed.  The live portal shows what is happening *right
now*: which tests are running, which just passed or failed, and how performance
metrics are trending over the last few minutes.

Think of it like the difference between a commit log and a CI pipeline view.
The commit log shows what shipped; the pipeline view shows what is building.

**Architecture:**

The portal is a single self-contained HTML file with embedded CSS and JS.
No external CDN, no build step, no framework.  It polls the mltk server API
every N seconds (configurable) and updates the DOM in place.

This design means:
- Works behind corporate firewalls (no outbound CDN requests).
- Works offline if the mltk server is on localhost.
- Can be served by any HTTP server, or opened directly as a file.
- No Node.js, no npm, no webpack -- just a Python function that returns HTML.

**Data flow:**

1. Portal JS calls ``GET /api/results?limit=50`` every ``refresh_seconds``.
2. Response is parsed and rendered into cards: one per test run.
3. A top banner shows aggregate health (pass rate, trend arrow, last update).
4. Failures are highlighted in red with expandable detail sections.

No external dependencies -- uses only ``html`` and ``json`` from stdlib.
"""

from __future__ import annotations

import html
from typing import Any


def create_portal_html(
    server_url: str = "http://localhost:8080",
    refresh_seconds: int = 30,
) -> str:
    """Generate a self-contained HTML page for live test result monitoring.

    **Why server-side HTML generation?**

    The portal HTML is generated by Python (not a JS build) because:
    1. It can be served from the mltk server without a separate static build.
    2. Server URL and refresh interval are baked in at generation time --
       no runtime configuration needed.
    3. The HTML can be saved to disk and opened locally.

    The generated page uses vanilla JavaScript with ``fetch()`` polling.
    All styles are inlined -- no external CSS files or CDN links.

    Args:
        server_url: Base URL of the mltk server to poll for results.
            The portal appends ``/api/results?limit=50`` to this URL.
            Must include the protocol (``http://`` or ``https://``).
        refresh_seconds: How often (in seconds) the portal fetches new data.
            Lower values give faster updates but increase server load.
            Recommended: 10--60 depending on test frequency.

    Returns:
        A complete HTML document as a string.  Write it to a file or serve
        it from an HTTP endpoint.

    Example::

        from mltk.server.portal import create_portal_html

        html_content = create_portal_html(
            server_url="http://ci-server:8080",
            refresh_seconds=15,
        )
        with open("portal.html", "w") as f:
            f.write(html_content)
    """
    # Escape user-provided values to prevent XSS if they ever contain
    # angle brackets or quotes (defense-in-depth).
    safe_url = html.escape(server_url, quote=True)
    safe_interval = int(refresh_seconds)

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>mltk Live Portal</title>
<style>
  :root {{
    --bg: #1e1e2e; --bg2: #2a2a3e; --bg3: #313145;
    --text: #e2e8f0; --text2: #94a3b8; --text3: #64748b;
    --green: #22c55e; --red: #ef4444; --yellow: #f59e0b; --blue: #60a5fa;
    --purple: #7c3aed; --purple-light: #a78bfa; --border: #383850;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: 'Cascadia Code', 'Fira Code', 'JetBrains Mono', monospace;
    background: var(--bg); color: var(--text); line-height: 1.6; font-size: 14px;
  }}
  .container {{ max-width: 1100px; margin: 0 auto; padding: 20px; }}

  /* Banner */
  .banner {{
    background: var(--bg2); border: 1px solid var(--border); border-radius: 10px;
    padding: 16px 24px; margin-bottom: 20px; display: flex;
    align-items: center; justify-content: space-between;
  }}
  .banner h1 {{ font-size: 20px; }}
  .banner h1 span {{ color: var(--purple-light); }}
  .banner .meta {{ font-size: 12px; color: var(--text3); text-align: right; }}

  /* Health bar */
  .health {{
    display: flex; gap: 16px; margin-bottom: 20px; flex-wrap: wrap;
  }}
  .health-card {{
    flex: 1; min-width: 140px; background: var(--bg2);
    border: 1px solid var(--border); border-radius: 8px; padding: 14px 18px;
  }}
  .health-card .label {{ font-size: 11px; color: var(--text3); text-transform: uppercase; }}
  .health-card .value {{ font-size: 26px; font-weight: 700; margin-top: 4px; }}
  .health-card .value.good {{ color: var(--green); }}
  .health-card .value.bad {{ color: var(--red); }}
  .health-card .value.warn {{ color: var(--yellow); }}

  /* Run list */
  .run-list {{ display: flex; flex-direction: column; gap: 10px; }}
  .run-card {{
    background: var(--bg2); border: 1px solid var(--border); border-radius: 8px;
    padding: 14px 18px; display: flex; align-items: center; gap: 16px;
  }}
  .run-card.fail {{ border-left: 3px solid var(--red); }}
  .run-card.pass {{ border-left: 3px solid var(--green); }}
  .run-status {{ font-size: 22px; width: 32px; text-align: center; }}
  .run-info {{ flex: 1; }}
  .run-info .project {{ font-weight: 600; }}
  .run-info .time {{ font-size: 12px; color: var(--text3); }}
  .run-stats {{ text-align: right; font-size: 13px; }}
  .run-stats .pass-count {{ color: var(--green); }}
  .run-stats .fail-count {{ color: var(--red); }}

  /* Footer */
  .footer {{
    margin-top: 24px; text-align: center; font-size: 11px; color: var(--text3);
  }}
</style>
</head>
<body>
<div class="container">
  <div class="banner">
    <h1><span>mltk</span> Live Portal</h1>
    <div class="meta">
      <div>Polling <code>{safe_url}</code></div>
      <div>Refresh: every <strong>{safe_interval}s</strong></div>
      <div id="last-update">Last update: --</div>
    </div>
  </div>

  <div class="health" id="health-bar">
    <div class="health-card">
      <div class="label">Total Runs</div>
      <div class="value" id="h-total">--</div>
    </div>
    <div class="health-card">
      <div class="label">Pass Rate</div>
      <div class="value" id="h-rate">--</div>
    </div>
    <div class="health-card">
      <div class="label">Latest Score</div>
      <div class="value" id="h-score">--</div>
    </div>
    <div class="health-card">
      <div class="label">Avg Duration</div>
      <div class="value" id="h-duration">--</div>
    </div>
  </div>

  <div class="run-list" id="run-list">
    <div class="run-card"><div class="run-info">Loading...</div></div>
  </div>

  <div class="footer">
    mltk Live Portal &mdash; auto-refreshes every {safe_interval} seconds
  </div>
</div>

<script>
(function() {{
  const SERVER = "{safe_url}";
  const INTERVAL = {safe_interval} * 1000;

  async function fetchData() {{
    try {{
      const resp = await fetch(SERVER + "/api/results?limit=50");
      if (!resp.ok) throw new Error("HTTP " + resp.status);
      return await resp.json();
    }} catch (e) {{
      console.error("Portal fetch error:", e);
      return null;
    }}
  }}

  function renderHealth(runs) {{
    const total = runs.length;
    const passed = runs.filter(r => r.failed === 0).length;
    const rate = total > 0 ? ((passed / total) * 100).toFixed(1) : "--";
    const latest = runs[0] || {{}};
    const avgDur = total > 0
      ? (runs.reduce((s, r) => s + (r.duration_ms || 0), 0) / total).toFixed(0)
      : "--";

    document.getElementById("h-total").textContent = total;

    const rateEl = document.getElementById("h-rate");
    rateEl.textContent = rate === "--" ? "--" : rate + "%";
    rateEl.className = "value " + (parseFloat(rate) >= 90 ? "good" : parseFloat(rate) >= 70 ? "warn" : "bad");

    const scoreEl = document.getElementById("h-score");
    scoreEl.textContent = latest.score != null ? latest.score.toFixed(1) : "--";

    document.getElementById("h-duration").textContent = avgDur === "--" ? "--" : avgDur + " ms";
    document.getElementById("last-update").textContent = "Last update: " + new Date().toLocaleTimeString();
  }}

  function esc(s) {{ const d = document.createElement("div"); d.textContent = s; return d.innerHTML; }}

  function renderRuns(runs) {{
    const container = document.getElementById("run-list");
    if (!runs || runs.length === 0) {{
      container.innerHTML = '<div class="run-card"><div class="run-info">No runs found.</div></div>';
      return;
    }}
    container.innerHTML = runs.map(r => {{
      const ok = r.failed === 0;
      const icon = ok ? "&#10003;" : "&#10007;";
      return '<div class="run-card ' + (ok ? "pass" : "fail") + '">'
        + '<div class="run-status">' + icon + '</div>'
        + '<div class="run-info">'
        + '  <div class="project">' + esc(r.project || "default") + '</div>'
        + '  <div class="time">' + esc(r.timestamp || "--") + '</div>'
        + '</div>'
        + '<div class="run-stats">'
        + '  <span class="pass-count">' + (r.passed || 0) + ' passed</span> / '
        + '  <span class="fail-count">' + (r.failed || 0) + ' failed</span>'
        + '</div></div>';
    }}).join("");
  }}

  async function tick() {{
    const data = await fetchData();
    if (data && Array.isArray(data.runs)) {{
      renderHealth(data.runs);
      renderRuns(data.runs);
    }} else if (data && Array.isArray(data)) {{
      renderHealth(data);
      renderRuns(data);
    }}
  }}

  tick();
  setInterval(tick, INTERVAL);
}})();
</script>
</body>
</html>"""


def get_portal_data(storage: Any) -> dict[str, Any]:
    """Get current portal data from storage (latest runs, trends, health).

    This function extracts and summarizes the data the portal needs from
    the mltk storage layer.  It is designed to be called from a server
    route handler, not from the portal HTML itself.

    **What the portal needs:**

    - ``runs`` -- the most recent test runs (up to 50), each with pass/fail
      counts, timestamp, project name, score, and duration.
    - ``summary`` -- aggregate statistics: total runs, overall pass rate,
      average duration, and the score of the latest run.
    - ``health`` -- a simple string label (``"healthy"``, ``"degraded"``,
      ``"failing"``) based on the recent pass rate.

    **Health thresholds:**

    - >= 90% pass rate: ``"healthy"`` -- the ML pipeline is working as expected.
    - >= 70% pass rate: ``"degraded"`` -- some tests are failing; investigate.
    - < 70% pass rate: ``"failing"`` -- significant problems; immediate action needed.

    Args:
        storage: An ``mltk.server.storage.Storage`` instance (or any object
            with a ``get_runs()`` method that returns a list of run dicts).
            Pass ``None`` to get an empty response (useful for testing).

    Returns:
        A dictionary with keys ``runs``, ``summary``, and ``health``.
    """
    if storage is None:
        return {
            "runs": [],
            "summary": {
                "total_runs": 0,
                "pass_rate": 0.0,
                "avg_duration_ms": 0.0,
                "latest_score": 0.0,
            },
            "health": "unknown",
        }

    # Fetch recent runs from storage
    try:
        runs = storage.get_runs(project=None, limit=50)
    except (AttributeError, TypeError):
        runs = []

    if not runs:
        return {
            "runs": [],
            "summary": {
                "total_runs": 0,
                "pass_rate": 0.0,
                "avg_duration_ms": 0.0,
                "latest_score": 0.0,
            },
            "health": "unknown",
        }

    # Compute summary statistics
    total_runs = len(runs)
    total_passed = sum(1 for r in runs if r.get("failed", 1) == 0)
    pass_rate = (total_passed / total_runs * 100) if total_runs > 0 else 0.0
    avg_duration = (
        sum(r.get("duration_ms", 0.0) for r in runs) / total_runs
        if total_runs > 0
        else 0.0
    )
    latest_score = runs[0].get("score", 0.0) if runs else 0.0

    # Determine health label
    if pass_rate >= 90.0:
        health = "healthy"
    elif pass_rate >= 70.0:
        health = "degraded"
    else:
        health = "failing"

    return {
        "runs": runs,
        "summary": {
            "total_runs": total_runs,
            "pass_rate": round(pass_rate, 1),
            "avg_duration_ms": round(avg_duration, 1),
            "latest_score": latest_score,
        },
        "health": health,
    }
