"""Test code generation -- turn scan findings into runnable pytest files.

The most valuable output of ``mltk scan``: self-contained pytest files
that reproduce every issue the scan found.  A developer runs the scan
once, gets a test file, and from that point on CI catches regressions
automatically -- no manual test-writing needed.

The generated code is:

- **Self-contained**: all imports, fixtures, and model loading in one
  file.  Copy it anywhere and ``pytest`` just works.
- **Environment-friendly**: model and data paths fall back to
  ``MLTK_MODEL_PATH`` / ``MLTK_DATA_PATH`` environment variables so
  the same file works locally and in CI.
- **Validated**: every generated file is parsed with ``ast.parse()``
  before being returned -- syntax errors are caught immediately,
  never shipped to the user.

Example::

    from mltk.scan.codegen import generate_test_file

    code = generate_test_file(
        findings,
        model_path="model.pkl",
        data_path="data.csv",
        target_col="label",
    )
    # code is a valid Python string ready for pytest
"""

from __future__ import annotations

import ast
import os
import re
import textwrap
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mltk.scan.finding import ScanFinding

__all__ = ["generate_test_file"]

# ------------------------------------------------------------------
# Severity ordering for deterministic test output
# ------------------------------------------------------------------
_SEVERITY_ORDER = {"critical": 0, "warning": 1, "info": 2}


# ------------------------------------------------------------------
# Internal helpers
# ------------------------------------------------------------------

def _sanitize_name(raw: str) -> str:
    """Turn an arbitrary string into a valid Python identifier.

    Strips non-alphanumeric characters, collapses runs of
    underscores, and ensures the result starts with a letter.
    """
    cleaned = re.sub(r"[^a-zA-Z0-9]", "_", raw)
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    if not cleaned or not cleaned[0].isalpha():
        cleaned = "t_" + cleaned
    return cleaned.lower()


def _indent(text: str, spaces: int = 8) -> str:
    """Indent every line of *text* by *spaces* spaces."""
    prefix = " " * spaces
    return textwrap.indent(text, prefix)


def _build_header() -> str:
    """Return the file-level docstring and imports block."""
    return textwrap.dedent("""\
        \"\"\"Auto-generated by mltk scan.

        Each test reproduces one issue found during scanning.
        Re-run with:  pytest {filepath}
        \"\"\"

        from __future__ import annotations

        import os

        import numpy as np
        import pandas as pd
        import pytest
    """)


def _build_model_fixture(
    model_path: str | None,
) -> str:
    """Return a pytest fixture that loads the model.

    Falls back to the ``MLTK_MODEL_PATH`` env var when no
    literal path was provided at generation time.
    """
    if model_path is not None:
        literal = repr(str(model_path))
    else:
        literal = "None"

    return textwrap.dedent(f"""\

        @pytest.fixture(scope="module")
        def model():
            \"\"\"Load the scanned model.

            Override with MLTK_MODEL_PATH env var.
            \"\"\"
            import joblib

            path = os.environ.get(
                "MLTK_MODEL_PATH", {literal},
            )
            if path is None:
                pytest.skip(
                    "Set MLTK_MODEL_PATH or pass --model"
                )
            return joblib.load(path)
    """)


def _build_data_fixture(
    data_path: str | None,
    target_col: str | None,
) -> str:
    """Return a pytest fixture that loads X and y.

    Falls back to the ``MLTK_DATA_PATH`` env var.  The target
    column defaults to ``"target"`` if not specified.
    """
    if data_path is not None:
        literal = repr(str(data_path))
    else:
        literal = "None"

    col = target_col if target_col else "target"

    return textwrap.dedent(f"""\

        @pytest.fixture(scope="module")
        def data():
            \"\"\"Load the scanned dataset.

            Override with MLTK_DATA_PATH env var.
            Returns (X, y) tuple.
            \"\"\"
            path = os.environ.get(
                "MLTK_DATA_PATH", {literal},
            )
            if path is None:
                pytest.skip(
                    "Set MLTK_DATA_PATH or pass --data"
                )
            df = pd.read_csv(path)
            target = {repr(col)}
            y = df[target].values
            X = df.drop(columns=[target])
            return X, y
    """)


def _build_test_method(
    index: int,
    finding: ScanFinding,
) -> str:
    """Build a single test method from a ScanFinding.

    Uses ``suggested_test`` when the scanner provided one.
    Otherwise falls back to a generic assertion based on the
    finding's result fields.
    """
    result = finding.result
    severity = result.severity.value
    safe_name = _sanitize_name(result.name)
    method_name = f"test_{index:03d}_{safe_name}"

    # Docstring from the finding
    docstring = (
        f"{result.message}\n\n"
        f"Scanner: {finding.scanner_name}\n"
        f"Severity: {severity}"
    )

    # Body: prefer scanner-provided code, else generic
    if finding.suggested_test.strip():
        body = finding.suggested_test.rstrip()
    else:
        body = _generic_body(finding)

    lines = [
        f"    def {method_name}(self, model, data):",
        f'        """{docstring}"""',
    ]
    # Indent the body relative to the method
    for line in body.splitlines():
        lines.append(f"        {line}")

    return "\n".join(lines)


def _generic_body(finding: ScanFinding) -> str:
    """Produce a fallback test body when no suggested_test."""
    result = finding.result
    details = result.details or {}

    parts: list[str] = [
        "# Auto-generated: verify this finding",
    ]

    if "metric" in details and "threshold" in details:
        metric = details["metric"]
        threshold = details["threshold"]
        parts.append(
            f"# Expected {metric} >= {threshold}"
        )
    parts.append(
        f"assert False, {repr(result.message)}"
    )
    return "\n".join(parts)


def _build_class(
    findings: list[ScanFinding],
) -> str:
    """Build the TestScanFindings class with all methods."""
    sorted_findings = sorted(
        findings,
        key=lambda f: _SEVERITY_ORDER.get(
            f.result.severity.value, 99
        ),
    )

    methods: list[str] = []
    for i, finding in enumerate(sorted_findings, start=1):
        methods.append(
            _build_test_method(i, finding),
        )

    body = "\n\n".join(methods)
    return (
        "\n\nclass TestScanFindings:\n"
        '    """Tests generated by mltk scan."""\n\n'
        f"{body}\n"
    )


def _validate_syntax(code: str) -> None:
    """Parse *code* with ``ast.parse`` to catch syntax errors.

    Raises:
        SyntaxError: If the generated code is not valid Python.
    """
    ast.parse(code, filename="<mltk-codegen>")


# ------------------------------------------------------------------
# Public API
# ------------------------------------------------------------------

def generate_test_file(
    findings: list[ScanFinding],
    model_path: str | None = None,
    data_path: str | None = None,
    target_col: str | None = None,
    output_path: str | None = None,
) -> str:
    """Generate a self-contained pytest file from scan findings.

    The generated file includes everything needed to run
    standalone:

    - All necessary imports (numpy, pandas, pytest, joblib).
    - A ``model`` fixture that loads the scanned model, with
      ``MLTK_MODEL_PATH`` env-var fallback.
    - A ``data`` fixture that loads the dataset and splits X/y,
      with ``MLTK_DATA_PATH`` env-var fallback.
    - One test method per finding inside a
      ``TestScanFindings`` class.
    - Methods ordered by severity (CRITICAL first).

    The complete source is validated with ``ast.parse()`` before
    returning.  If a scanner produced invalid ``suggested_test``
    code, this function raises ``SyntaxError`` immediately --
    broken tests are never written to disk.

    Args:
        findings: List of ScanFinding objects from a scan run.
            An empty list produces a file with fixtures but no
            test methods (useful as a template).
        model_path: Filesystem path to the model file
            (e.g., ``"model.pkl"``).  Baked into the fixture as
            a default; overridable via ``MLTK_MODEL_PATH``.
        data_path: Filesystem path to the CSV dataset.  Baked
            into the fixture as a default; overridable via
            ``MLTK_DATA_PATH``.
        target_col: Name of the target/label column in the CSV.
            Defaults to ``"target"`` when not specified.
        output_path: If provided, the generated code is also
            written to this file.  Parent directories are
            created automatically.

    Returns:
        The generated Python source code as a string.

    Raises:
        SyntaxError: If the assembled code fails
            ``ast.parse()`` validation.

    Example::

        from mltk.scan.codegen import generate_test_file

        code = generate_test_file(
            report.findings,
            model_path="models/clf.pkl",
            data_path="data/test.csv",
            target_col="label",
            output_path="tests/test_scan_results.py",
        )
        print(f"Generated {len(code)} chars of test code")
    """
    parts: list[str] = [
        _build_header(),
        _build_model_fixture(model_path),
        _build_data_fixture(data_path, target_col),
    ]

    if findings:
        parts.append(_build_class(findings))
    else:
        parts.append(
            "\n\n# No findings -- scan was clean.\n"
        )

    code = "\n".join(parts)

    # Gate: never return invalid Python
    _validate_syntax(code)

    if output_path is not None:
        parent = os.path.dirname(output_path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as fh:
            fh.write(code)

    return code
