"""FDA 21 CFR Part 11 audit trail generation from mltk test results."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from mltk.report._helpers import _load_results


def generate_fda_audit_trail(
    results_path: str | Path,
    system_name: str = "AI System",
    operator: str = "QA Engineer",
    output_path: str | Path = "fda-audit-trail.md",
) -> Path:
    """Generate an FDA 21 CFR Part 11 compliant audit trail.

    Produces a Markdown document with: system info, operator ID,
    timestamps, test evidence, digital signature placeholder, and
    version control metadata.

    Args:
        results_path: Path to mltk results JSON.
        system_name: Name of the AI/ML system under test.
        operator: Name or ID of the test operator.
        output_path: Destination for the Markdown file.

    Returns:
        Path to the generated audit trail file.
    """
    results = _load_results(results_path)
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total = len(results)
    passed = sum(1 for r in results if r.get("passed"))
    failed = total - passed

    lines: list[str] = [
        "# FDA 21 CFR Part 11 — Audit Trail",
        "",
        "## 1. System Information",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| System Name | {system_name} |",
        f"| Audit Date | {now} |",
        "| Generated By | mltk |",
        "",
        "## 2. Operator Identification",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Operator | {operator} |",
        f"| Timestamp | {now} |",
        "",
        "## 3. Test Evidence",
        "",
        f"**Summary**: {passed}/{total} passed, {failed} failed",
        "",
        "| # | Test Name | Status | Severity | Message |",
        "|---|-----------|--------|----------|---------|",
    ]

    for i, r in enumerate(results, 1):
        name = r.get("name", "unknown")
        status = "PASS" if r.get("passed") else "FAIL"
        severity = r.get("severity", "info")
        message = r.get("message", "").replace("|", "/")
        lines.append(f"| {i} | {name} | {status} | {severity} | {message} |")

    lines.extend([
        "",
        "## 4. Digital Signature",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Signed By | _{operator} (pending)_ |",
        f"| Date | {now} |",
        "| Signature | ______________________ |",
        "",
        "## 5. Regulatory Notes",
        "",
        "This audit trail is generated in compliance with FDA 21 CFR Part 11 "
        "requirements for electronic records. All test results are timestamped, "
        "attributed to an identified operator, and include pass/fail evidence "
        "with severity classifications.",
        "",
        "---",
        f"*Generated by mltk on {now}*",
    ])

    out = Path(output_path)
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
